from tkinter import *

ventana = Tk()
ventana.title("nueva ventana")
ventana.geometry("900x500")
ventana.config(background="dark turquoise")
etiqueta = Label(ventana, text="Automatas", bg="gold", fg="black")
etiqueta.pack()
imagenAuto = PhotoImage(file="Palindromo Impar.gv.png")
lbImage = Label(ventana, image=imagenAuto)
lbImage.pack(side="left")
var =  StringVar(ventana)
var.set("rojo")
opciones = ["azul", "rosa", "amarillo"]
opcion= OptionMenu(ventana, var, *opciones)
opcion.config(width=20)
opcion.pack(side="right")
botonDiadrama = Button(ventana, text="prueba", command=imagenAuto)
botonDiadrama.pack()
ventana.mainloop()